version: "2"

services:
  web:
    build: .
    container_name: ipa-server-self
    restart: always
    environment:
      - NODE_ENV=production
      - PUBLIC_URL=https://ipa.cybex.io
      - ACCESS_KEY=cybexipaupload
    ports:
      - "9008:8080"
    volumes:
      - "~/docker/data/ipa-server:/app/upload"
